"""`lf assets` — the Mixamo → GLB → Godot pipeline.

  scan     what clips Fighter.gd wants vs. what is actually on disk (no API call)
  convert  write/run a headless Blender script that turns every .fbx into a
           clean single-clip .glb
  wire     rebuild the `external_animations` dictionary from what is on disk,
           using the model only to resolve ambiguous filenames
"""

from __future__ import annotations

import re
import shutil
import subprocess
from pathlib import Path

from .azure_client import AzureClient, extract_json
from .blender_runner import BlenderRunner, find_blender, resolve  # noqa: F401
from .config import OUT_DIR, PROJECT_ROOT

ANIM_DIR = PROJECT_ROOT / "animations"
FIGHTER = PROJECT_ROOT / "scripts" / "Fighter.gd"

_EXT_ANIMS = re.compile(
    r"(@export var external_animations: Dictionary = \{)(?P<body>.*?)(^\})",
    re.DOTALL | re.MULTILINE,
)
_ENTRY = re.compile(r'"(?P<clip>[^"]+)"\s*:\s*"(?P<path>[^"]+)"')


# -- helpers ----------------------------------------------------------------


def current_mapping() -> dict[str, str]:
    if not FIGHTER.is_file():
        return {}
    text = FIGHTER.read_text(encoding="utf-8", errors="replace")
    m = _EXT_ANIMS.search(text)
    if not m:
        return {}
    return {e.group("clip"): e.group("path") for e in _ENTRY.finditer(m.group("body"))}


def glb_files() -> list[str]:
    if not ANIM_DIR.is_dir():
        return []
    return sorted(p.name for p in ANIM_DIR.glob("*.glb"))


def fbx_files() -> list[str]:
    if not ANIM_DIR.is_dir():
        return []
    return sorted(p.name for p in ANIM_DIR.glob("*.fbx"))


# -- scan -------------------------------------------------------------------


def run_scan(args) -> int:
    mapping = current_mapping()
    present = set(glb_files())
    fbx = fbx_files()

    print("Animation pipeline status")
    print("=" * 62)
    print(f"  animations/   {len(present)} .glb   {len(fbx)} .fbx awaiting conversion")
    if not mapping:
        print("\n  ! Could not read external_animations from scripts/Fighter.gd")
        return 1

    ok, missing = [], []
    for clip, res_path in sorted(mapping.items()):
        fname = res_path.rsplit("/", 1)[-1]
        (ok if fname in present else missing).append((clip, fname))

    print(f"\n  Mapped and present ({len(ok)}):")
    for clip, fname in ok:
        print(f"    ✓ {clip:<12} {fname}")

    if missing:
        print(f"\n  Mapped but MISSING ({len(missing)}) — these states stay silent in game:")
        for clip, fname in missing:
            print(f"    ✗ {clip:<12} {fname}")

    referenced = {p.rsplit("/", 1)[-1] for p in mapping.values()}
    unused = sorted(present - referenced)
    if unused:
        print(f"\n  On disk but unmapped ({len(unused)}):")
        for fname in unused:
            print(f"    · {fname}")
        print("\n    Map them with:  python3 automation/lf.py assets wire")

    if fbx:
        print(f"\n  .fbx needing conversion ({len(fbx)}):")
        for fname in fbx:
            print(f"    · {fname}")
        print("\n    Convert with:  python3 automation/lf.py assets convert --run")

    runner, why = resolve(getattr(args, "blender", None))
    if runner:
        print(f"\n  Blender: {runner.describe()}")
    else:
        print("\n  Blender: " + why.replace("\n", "\n  "))
    return 0


# -- convert ----------------------------------------------------------------

CONVERT_TEMPLATE = '''"""
Headless FBX -> single-clip GLB conversion for Little Fighters.

Generated by: python3 automation/lf.py assets convert
Run headless:  blender --background --python automation/out/convert_animations.py
Or from Blender's Scripting tab: open this file and press Run Script.

Each FBX is imported into a freshly emptied scene so every exported .glb
carries exactly one animation — which is what Fighter.gd's loader expects.
"""

import bpy
import glob
import os
import sys

PROJECT_ROOT = r"{project_root}"
ANIM_DIR = os.path.join(PROJECT_ROOT, "animations")
OVERWRITE = {overwrite}


def clear_scene():
    for obj in list(bpy.data.objects):
        bpy.data.objects.remove(obj, do_unlink=True)
    for block in (bpy.data.actions, bpy.data.armatures, bpy.data.meshes,
                  bpy.data.materials, bpy.data.images):
        for item in list(block):
            if item.users == 0:
                block.remove(item)


def view3d_override():
    """The FBX importer wants a 3D viewport context when run with a UI."""
    for window in bpy.context.window_manager.windows:
        for area in window.screen.areas:
            if area.type == 'VIEW_3D':
                for region in area.regions:
                    if region.type == 'WINDOW':
                        return {{"window": window, "screen": window.screen,
                                "area": area, "region": region}}
    return None


def main():
    files = sorted(glob.glob(os.path.join(ANIM_DIR, "*.fbx")))
    print("[convert] %d FBX files in %s" % (len(files), ANIM_DIR))
    override = view3d_override()
    done = skipped = failed = 0

    for fbx in files:
        base = os.path.splitext(os.path.basename(fbx))[0]
        out = os.path.join(ANIM_DIR, base + ".glb")
        if os.path.exists(out) and not OVERWRITE:
            print("[convert] skip (exists): %s" % os.path.basename(out))
            skipped += 1
            continue
        try:
            clear_scene()
            if override:
                with bpy.context.temp_override(**override):
                    bpy.ops.import_scene.fbx(filepath=fbx)
            else:
                bpy.ops.import_scene.fbx(filepath=fbx)
            bpy.ops.export_scene.gltf(
                filepath=out,
                export_format='GLB',
                export_animations=True,
                export_animation_mode='ACTIONS',
                export_skins=True,
                export_yup=True,
            )
            print("[convert] ok: %s -> %s" % (os.path.basename(fbx), os.path.basename(out)))
            done += 1
        except Exception as exc:
            print("[convert] FAILED %s: %s" % (os.path.basename(fbx), exc))
            failed += 1

    print("[convert] DONE  converted=%d skipped=%d failed=%d" % (done, skipped, failed))
    if failed:
        sys.exit(1)


main()
'''


def run_convert(args) -> int:
    runner, why = resolve(getattr(args, "blender", None),
                          getattr(args, "docker", False),
                          getattr(args, "image", None))
    if runner is None and args.run:
        print("  ! " + why)
        return 1

    root = runner.project_root if runner else str(PROJECT_ROOT)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    script = OUT_DIR / "convert_animations.py"
    script.write_text(
        CONVERT_TEMPLATE.format(project_root=root, overwrite=bool(args.overwrite)),
        encoding="utf-8",
    )
    print(f"  Wrote {script.relative_to(PROJECT_ROOT)}")

    pending = fbx_files()
    if not pending:
        print("  No .fbx files in animations/ — nothing to convert.")
        return 0
    print(f"  {len(pending)} .fbx queued: " + ", ".join(pending[:8])
          + (" …" if len(pending) > 8 else ""))

    if not args.run:
        print("\n  Run it with:  python3 automation/lf.py assets convert --run")
        print("  Or open it in Blender's Scripting tab and press Run Script.")
        return 0

    print(f"\n  Running via {runner.describe()}")
    proc = subprocess.run(runner.command(script), capture_output=True, text=True)
    for line in proc.stdout.splitlines():
        if "[convert]" in line:
            print("    " + line)
    if proc.returncode != 0:
        print("\n  ! Blender exited non-zero. Last stderr:")
        print("    " + "\n    ".join(proc.stderr.strip().splitlines()[-15:]))
        return 1
    print("  Done. Godot will reimport the new .glb files next time you focus the editor.")
    return 0


# -- wire -------------------------------------------------------------------

WIRE_SYSTEM = """You map animation filenames onto a fighting game's clip names.

The game needs exactly these clip names:
idle, walk, run, jump, punch, kick, dropkick, hit, block, dash, knockdown, getup, death

Given the .glb files present, choose the single best file for each clip name.
Prefer an obvious filename match. A file may be used for at most one clip.
If no reasonable file exists for a clip, map it to null — never invent a filename.

Reply with JSON only, no prose:
{"idle": "breathing.glb", "walk": "walking.glb", "run": null, ...}
"""


def run_wire(args) -> int:
    present = glb_files()
    if not present:
        print("  No .glb files in animations/ — run `assets convert` first.")
        return 1

    mapping = current_mapping()
    print(f"  {len(present)} .glb on disk, {len(mapping)} currently mapped.")

    prompt = (
        "Files present in animations/:\n"
        + "\n".join(f"  {n}" for n in present)
        + "\n\nCurrent mapping (clip -> file), which you may keep or improve:\n"
        + "\n".join(f"  {c} -> {p.rsplit('/', 1)[-1]}" for c, p in sorted(mapping.items()))
        + "\n\nReturn the complete mapping as JSON."
    )

    if args.dry_run:
        print("  --dry-run: not calling the API.")
        return 0

    client = AzureClient()
    reply = client.respond(prompt, system=WIRE_SYSTEM, command="assets-wire",
                           max_output_tokens=2000)
    try:
        proposed = extract_json(reply)
    except Exception as exc:
        print(f"  ! Could not parse the model's reply: {exc}")
        (OUT_DIR / "wire_reply.txt").write_text(reply, encoding="utf-8")
        return 1

    if not isinstance(proposed, dict):
        print("  ! Model returned something other than an object.")
        return 1

    valid = set(present)
    lines, changed = [], 0
    for clip in ["idle", "walk", "run", "jump", "punch", "kick", "dropkick",
                 "hit", "block", "dash", "knockdown", "getup", "death"]:
        fname = proposed.get(clip)
        if not isinstance(fname, str) or fname not in valid:
            print(f"    – {clip:<10} (no file)")
            continue
        res = f"res://animations/{fname}"
        was = mapping.get(clip)
        mark = " " if was == res else "*"
        if was != res:
            changed += 1
        print(f"    {mark} {clip:<10} {fname}")
        lines.append(f'\t"{clip}": "{res}",')

    if not lines:
        print("  Nothing mappable.")
        return 1

    new_block = "@export var external_animations: Dictionary = {\n" + "\n".join(lines) + "\n}"
    text = FIGHTER.read_text(encoding="utf-8")
    patched = _EXT_ANIMS.sub(lambda _: new_block, text, count=1)

    if patched == text:
        print("\n  No change needed — Fighter.gd already matches.")
        return 0

    out = OUT_DIR / "assets-wire"
    out.mkdir(parents=True, exist_ok=True)
    dest = out / "scripts" / "Fighter.gd"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(patched, encoding="utf-8")
    print(f"\n  {changed} mapping(s) changed. Proposal → automation/out/assets-wire/")

    if args.apply:
        backup = out / "_backup" / "scripts"
        backup.mkdir(parents=True, exist_ok=True)
        shutil.copy2(FIGHTER, backup / "Fighter.gd")
        FIGHTER.write_text(patched, encoding="utf-8")
        print("  Applied to scripts/Fighter.gd (original backed up).")
    else:
        print("  Apply with:  python3 automation/lf.py apply assets-wire")
    return 0
